### ISSUE TITLE
Application tried to open a nil modal view controller

### ISSUE THREAD

**Issue by zzzzakhar** [bamlab/react-native-braintree-payments-drop-in#12]
I am trying to implement BraintreeDropIn in my react native app for both iOS and Android but when calling the method BraintreeDropIn.show with the token, etc. in react native I get the following error on the simulator:

Exception 'Application tried to open a nil modal view controller on target <UIViewController: 0x7fa8ece0a980>.' was thrown while invoking show on target RNBraintreeDropIn with params ...

**Comment by disappearer** [comment]
Hello there, have you found a solution for this, by any chance?

**Comment by Minishlink** [comment]
Hello, this happens when your client token is invalid
