### ISSUE TITLE
null is not an object on iOS

### ISSUE THREAD

**Issue by epurban** [bamlab/react-native-braintree-payments-drop-in#15]
I'm trying to implement this using the basic flow as indicated in the README:
![image](https://user-images.githubusercontent.com/22136514/57349241-5da0e700-7127-11e9-907c-0cf12d001ded.png)

When I build and run, and click the button that calls the function paymentPanel, I get this error:
<img width="315" alt="Screen Shot 2019-05-08 at 12 16 54 AM" src="https://user-images.githubusercontent.com/22136514/57349263-6b566c80-7127-11e9-917a-a3b8170656a0.png">

I have no idea what the hell this issue is and I need to fix it asap. Thank you!

**Comment by Minishlink** [comment]
Hello, are you installing the module using the cocoapods methods or the manual installation using the Xcode pbxproj file?

**Comment by epurban** [comment]
@Minishlink I'm installing using cocoapods

**Comment by Minishlink** [comment]
Do you have that exact line in your `Podfile`?

```
pod 'RNBraintreeDropIn', :path => '../node_modules/react-native-braintree-payments-drop-in/ios'
```

Did you ran `bundle exec pod install`? (or `pod install` if you don't have local deps)

**Comment by pateljigar7210** [comment]
how to get client token ?

**Comment by Minishlink** [comment]
@pateljigar7210 See https://developers.braintreepayments.com/guides/drop-in/setup-and-integration/javascript/v3#configuration
