### ISSUE TITLE
Crash the app in react native 0.59.4

### ISSUE THREAD

**Issue by emurigar** [bamlab/react-native-braintree-payments-drop-in#16]
I updated to the lastest version of react native and in IOS when I push the button that it uses this code crash the app and it closes. I tried with the versions 1.0.1 ( my previous version) and 1.0.4

In Android the same button go well.

Before to the update I used 0.55.4 version and in both SO went well.

**Comment by emurigar** [comment]
With react native version 0.55.9 we have the same crash.

**Comment by Minishlink** [comment]
Can you try with latest version? Please check your client token also.

**Comment by emurigar** [comment]
I have the same error, I'm trying with the react native version 0.55.9

**Comment by emurigar** [comment]
If you want I can do any other test. The problem in IOS is that I can not access to see the log

**Comment by javiervaldeslz** [comment]
I am having the same issue with the new version, tested with react native 0.59 and 0.60

**Comment by anand-digit88** [comment]
2019-09-03 18:51:22.813 [info][tid:com.facebook.react.JavaScript] Error happenedTypeError: null is not an object (evaluating '_reactNativeBraintreePaymentsDropIn.default.show')
2019-09-03 18:51:22.812823+0530 app[18202:2045133] Error happenedTypeError: null is not an object (evaluating '_reactNativeBraintreePaymentsDropIn.default.show')

**Comment by emurigar** [comment]
@Minishlink , have you been able to see it?

**Comment by emurigar** [comment]
I fixed the problem, in the previous version the field amount in threeDSecure json it was a value from a state (this.state.price) now it needs to pase a float: parseFloat(this.state.price)
