### ISSUE TITLE
iOS 13 Font changes?

### ISSUE THREAD

**Issue by chppatel** [bamlab/react-native-braintree-payments-drop-in#18]
While the package works wonderfully in iOS 13. We've noticed the fonts are off between iOS 12 vs iOS 13. Has anyone noticed this?

**Comment by Minishlink** [comment]
There's a fix on the Braintree Drop In repo (https://github.com/braintree/braintree-ios-drop-in/blob/f64b0b999b16b1c6395a09eb61544d2801dc62bc/CHANGELOG.md#730-2019-08-09)

If you can send a PR here to upgrade the BraintreeDropIn iOS dependancy (in the podspec), and that you test it, I'll be grateful.

**Comment by mspasov** [comment]
Did a quick test, it works with Braintree 4.30 and BraintreeDropIn 7.4.0.
