### ISSUE TITLE
Question: can I pass the nonce back to the Braintree drop in UI?

### ISSUE THREAD

**Issue by ShaharyarMaroof** [bamlab/react-native-braintree-payments-drop-in#24]
@Minishlink I was wondering if I can pass the nonce back to the drop in ui so that if the user has previously entered any card info, they can go straight to the card info screen rather than selecting a payment method as they do on the first time use?

**Comment by ShaharyarMaroof** [comment]
Any updates on this?

**Comment by Minishlink** [comment]
Not sure what you mean?

**Comment by ShaharyarMaroof** [comment]
@Minishlink, so the first the time the user opens the braintree drop in UI and provides card info to get a nonce token, which is passed to my server.
Let's suppose, I open the braintree drop in UI again, this time I want to prepopulate the previously entered card info in the drop in UI. I will have to pass the nonce token back to the library right? Will that be done by passing the nonce token to the clientToken key?

**Comment by Minishlink** [comment]
As far as I remember, when you call the Braintree Drop-In with the same client token, it will show the registered card if the user already has one. But this can only work if on the server side you save the card on Braintree for this specific customer.

**Comment by ShaharyarMaroof** [comment]
Okay, will try it out, thanks for the help! (Y)

**Comment by ShaharyarMaroof** [comment]
It worked by passing in the clientToken I get from my server. thanks!
