### ISSUE TITLE
Question: Can I hide the paypal option from the dropin ui?

### ISSUE THREAD

**Issue by ShaharyarMaroof** [bamlab/react-native-braintree-payments-drop-in#26]
@Minishlink I was wondering how to hide certain payment methods from the DropIn UI? I don't need the paypal option, but I didn't find anything in the documentation regarding this?

**Comment by Minishlink** [comment]
You need to disable it on the Braintree console ("Processing" page). I don't know if you can disable it in sandbox mode though.

**Comment by ShaharyarMaroof** [comment]
Thanks! Yes I think you can't disable it in the sandbox mode.
