### ISSUE TITLE
Get a Error when build project, any help ?

### ISSUE THREAD

**Issue by wgltony** [bamlab/react-native-braintree-payments-drop-in#3]
Did everything in the instruction, Below is error log when build project, please help! Thanks.

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_BTPaymentFlowDriver", referenced from:
      objc-class-ref in libBraintreeDropIn.a(BTCardFormViewController.o)
  "_OBJC_CLASS_$_BTThreeDSecureRequest", referenced from:
      objc-class-ref in libBraintreeDropIn.a(BTCardFormViewController.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Minishlink** [comment]
Hello, here's some things that can fix this:

- Make sure you ran pod install (your Podfile.lock should have changed)
- clear your ios/build folder
- clear XCode derived data

If this doesn't work, I'll need the content of your Podfile.lock anf might need a reproducible repository.

**Comment by maxweb4u** [comment]
Hello, I have the same bug and clearing doesn't work. Here is my podfile.lock
[Podfile.lock.zip](https://github.com/bamlab/react-native-braintree-payments-drop-in/files/2092026/Podfile.lock.zip)
